import { Command } from "commander";
import { getBackend } from "../backends";
import { loadConfig } from "../config";
import { writeEnvFile, mergeEnvContent } from "../env-writer";
import { readFile, writeFile } from "fs/promises";
import { resolve, join, basename } from "path";

export const pullCommand = new Command("pull")
  .description("Pull keys from your password manager and generate env files")
  .option("-e, --env <env>", "environment (dev/prod)", "prod")
  .option("--vault <vault>", "Vault or folder name", "shipkey")
  .option("--project <name>", "project name (defaults to directory name)")
  .option("--no-envrc", "skip .envrc generation")
  .option("--no-dev-vars", "skip .dev.vars generation")
  .argument("[dir]", "project directory", ".")
  .action(async (dir: string, opts) => {
    const projectRoot = resolve(dir);
    const project = opts.project || basename(projectRoot);
    const env = opts.env;
    const vault = opts.vault;

    let backendName = "1password";
    try {
      const config = await loadConfig(projectRoot);
      if (config.backend) backendName = config.backend;
    } catch {
      // No config file — use default backend
    }
    const backend = getBackend(backendName);

    if (!(await backend.isAvailable())) {
      console.error(
        `Error: ${backend.name} CLI not available. Run 'shipkey setup' for installation instructions.`
      );
      process.exit(1);
    }

    console.log(`Pulling keys for ${project}.${env}...\n`);

    const refs = await backend.list(project, env);

    if (refs.length === 0) {
      console.log(`No keys found for ${project}.${env} in vault ${vault}.`);
      return;
    }

    // Read all values
    const entries: { key: string; value: string; ref: typeof refs[0] }[] = [];
    for (const ref of refs) {
      try {
        const value = await backend.read(ref);
        const envKey = ref.field;
        entries.push({ key: envKey, value, ref });
        console.log(`  ✓ Restored ${envKey}`);
      } catch (err) {
        console.error(
          `  ✗ ${ref.provider}/${ref.field} — ${err instanceof Error ? err.message : err}`
        );
      }
    }

    if (entries.length === 0) return;

    // Write env file (.env / .env.local / .dev.vars — auto-detected, merge-safe)
    const envVars: Record<string, string> = {};
    for (const e of entries) {
      envVars[e.key] = e.value;
    }
    const envFile = await writeEnvFile(projectRoot, envVars);
    console.log(`\n  ✓ Updated ${envFile}`);

    // Generate .envrc
    if (opts.envrc) {
      const envrcContent = [
        `# Auto-generated by shipkey — do not edit manually`,
        `# Project: ${project}  Environment: ${env}`,
        "",
        ...entries.map((e) => {
          const inlineRef = backend.buildInlineRef?.(e.ref);
          if (inlineRef) {
            return `export ${e.key}=$(op read "${inlineRef}")`;
          }
          // Backend doesn't support inline refs — write value directly
          const escaped = e.value
            .replace(/\\/g, "\\\\")
            .replace(/"/g, '\\"')
            .replace(/\$/g, "\\$")
            .replace(/`/g, "\\`");
          return `export ${e.key}="${escaped}"`;
        }),
        "",
      ].join("\n");

      await writeFile(join(projectRoot, ".envrc"), envrcContent);
      console.log(`\n  ✓ Generated .envrc`);
    }

    // Generate .dev.vars (merge with existing content)
    // Skip if writeEnvFile already wrote to .dev.vars (Cloudflare Workers project)
    if (opts.devVars && envFile !== ".dev.vars") {
      const devVarsPath = join(projectRoot, ".dev.vars");
      let existingContent = "";
      try {
        existingContent = await readFile(devVarsPath, "utf-8");
      } catch {
        // File doesn't exist yet — start fresh
      }

      // If file is empty, seed with header
      if (!existingContent || existingContent.trim() === "") {
        existingContent = [
          `# Auto-generated by shipkey — do not edit manually`,
          `# Project: ${project}  Environment: ${env}`,
          "",
        ].join("\n");
      }

      const devVarsContent = mergeEnvContent(existingContent, envVars);
      await writeFile(devVarsPath, devVarsContent);
      console.log(`  ✓ Generated .dev.vars`);
    }

    console.log(`\nRestored ${entries.length} keys for ${project}.${env}`);
  });

